# Generated by Django 4.1.2 on 2022-10-12 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0003_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("update", models.DateTimeField(auto_now=True, null=True)),
                ("file", models.ImageField(null=True, upload_to="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
        migrations.AddField(
            model_name="postphoto",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_photos",
                to="posts.post",
            ),
        ),
    ]
