# Generated by Django 4.1.2 on 2022-10-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_secret_account",
            field=models.BooleanField(default=False),
        ),
    ]
