# Generated by Django 4.1.2 on 2022-10-12 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stories", "0001_initial"),
        ("posts", "0004_postphoto_post_tags_delete_photo_postphoto_post"),
        ("conversations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("update", models.DateTimeField(auto_now=True, null=True)),
                (
                    "alarmType",
                    models.CharField(
                        choices=[
                            ("follow", "Follow"),
                            ("post", "Post"),
                            ("story", "Story"),
                            ("message", "Message"),
                        ],
                        default="post",
                        max_length=7,
                    ),
                ),
                ("is_checked", models.BooleanField(default=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm",
                        to="posts.post",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
