# Generated by Django 4.1.2 on 2022-10-10 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("follows", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="followPerson",
            field=models.ManyToManyField(
                blank=True, related_name="followsPerson", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="followerPerson",
            field=models.ManyToManyField(
                blank=True, related_name="followerPerson", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
