# Generated by Django 4.1.2 on 2022-10-12 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("follows", "0002_alter_follow_followperson_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="followPerson",
        ),
        migrations.RemoveField(
            model_name="follower",
            name="followerPerson",
        ),
        migrations.AddField(
            model_name="follow",
            name="follow",
            field=models.ManyToManyField(
                blank=True, related_name="followList", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="follower",
            name="follower",
            field=models.ManyToManyField(
                blank=True, related_name="followerList", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
