# Generated by Django 4.1.2 on 2022-10-12 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommendList",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recommendList",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
