# Generated by Django 4.1.2 on 2022-10-12 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("likes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="count",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.AddField(
            model_name="like",
            name="userList",
            field=models.ManyToManyField(
                blank=True, related_name="userList", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
